"""v0.88 #8 — auto-generated overview sections wear a visual `[!info]` callout."""

from __future__ import annotations

import json
from pathlib import Path
from types import SimpleNamespace

from research_hub.vault.hub_overview import (
    BRIEF_HEADING,
    MOC_HEADING,
    PAPERS_HEADING,
    _generated_brief_body,
    _generated_moc_body,
    _render_papers_section,
    _wrap_auto_section,
    populate_overview,
)


def test_wrap_auto_section_prepends_callout() -> None:
    body = "- item-a\n- item-b\n"
    wrapped = _wrap_auto_section(body)
    assert wrapped.startswith("> [!info] Auto-generated by `populate_overview`")
    assert body in wrapped


def test_wrap_auto_section_is_idempotent() -> None:
    body = "- item-a\n"
    once = _wrap_auto_section(body)
    twice = _wrap_auto_section(once)
    assert once == twice  # never prepends a second copy


def test_wrap_auto_section_empty_body_pass_through() -> None:
    assert _wrap_auto_section("") == ""


def test_render_papers_section_wears_callout(tmp_path: Path) -> None:
    raw = tmp_path / "raw" / "demo"
    raw.mkdir(parents=True)
    (raw / "alpha2024.md").write_text(
        '---\ntitle: "alpha"\nyear: 2024\nauthors: "Alpha, A"\n---\n# alpha\n',
        encoding="utf-8",
    )
    rendered = _render_papers_section(tmp_path, "demo")
    assert rendered.startswith("> [!info] Auto-generated by `populate_overview`")
    assert "[[alpha2024]]" in rendered


def test_generated_brief_body_wears_callout(tmp_path: Path) -> None:
    brief = tmp_path / "notebooklm-brief-20260513T000000Z.md"
    brief.write_text("...", encoding="utf-8")
    body = _generated_brief_body(brief)
    assert body is not None
    assert body.startswith("> [!info] Auto-generated by `populate_overview`")
    assert "[[notebooklm-brief-20260513T000000Z]]" in body


def test_generated_moc_body_wears_callout() -> None:
    body = _generated_moc_body(["LLM-Agents", "Water-Resources"])
    assert body is not None
    assert body.startswith("> [!info] Auto-generated by `populate_overview`")
    assert "[[LLM-Agents]]" in body
    assert "[[Water-Resources]]" in body


def test_generated_moc_body_empty_returns_none() -> None:
    assert _generated_moc_body(None) is None
    assert _generated_moc_body([]) is None
    assert _generated_moc_body(["", "   "]) is None


def test_populate_overview_emits_callout_in_papers_section(tmp_path: Path) -> None:
    raw = tmp_path / "raw" / "demo"
    raw.mkdir(parents=True)
    (raw / "x2024.md").write_text(
        '---\ntitle: "x"\nyear: 2024\nauthors: "X, X"\n---\n# x\n',
        encoding="utf-8",
    )
    populate_overview(cluster_slug="demo", vault_root=tmp_path)
    text = (tmp_path / "hub" / "demo" / "00_overview.md").read_text(encoding="utf-8")
    # Each auto section must have the callout
    assert text.count("> [!info] Auto-generated by `populate_overview`") >= 1
    # Papers section specifically
    papers_idx = text.find(f"## {PAPERS_HEADING}")
    assert papers_idx >= 0
    callout_in_section = text[papers_idx:].find("> [!info]")
    assert 0 < callout_in_section < 200  # appears close after the heading
