@echo off
REM ============================================================
REM Weekly research-hub BSE auto-pull
REM Triggered by Windows Task Scheduler every Mon 09:00 local time
REM Writes a brief summary report to <vault>/logs/weekly_pull_*.md
REM ============================================================

setlocal EnableDelayedExpansion

REM --- config ---
set VAULT=C:\Users\wenyu\knowledge-base
set CLUSTER=llm-agents-behavioral-science-environmental-interaction
set TOPIC=AI agent society environment interaction
set MAX_PAPERS=10

REM --- timestamp for batch label + log filename ---
for /f "tokens=2 delims==." %%a in ('wmic os get LocalDateTime /value 2^>nul') do set DT=%%a
set DATE_STR=%DT:~0,4%-%DT:~4,2%-%DT:~6,2%
set BATCH_LABEL=weekly-%DATE_STR%
set LOG_DIR=%VAULT%\logs
set RUN_LOG=%LOG_DIR%\weekly_pull_run_%DATE_STR%.log
set REPORT=%LOG_DIR%\weekly_pull_%DATE_STR%.md

if not exist "%LOG_DIR%" mkdir "%LOG_DIR%"

REM --- run auto pipeline ---
cd /d "%VAULT%"
echo [%DATE% %TIME%] Starting weekly BSE pull (batch=%BATCH_LABEL%) > "%RUN_LOG%"
python -W ignore -m research_hub auto "%TOPIC%" ^
    --cluster %CLUSTER% ^
    --max-papers %MAX_PAPERS% ^
    --full-auto ^
    --no-nlm ^
    --append ^
    --batch-label "%BATCH_LABEL%" >> "%RUN_LOG%" 2>&1
set RC=%ERRORLEVEL%
echo [%DATE% %TIME%] auto exited with rc=%RC% >> "%RUN_LOG%"

REM --- write a short markdown report by greping the run log ---
echo # Weekly BSE auto-pull %DATE_STR% > "%REPORT%"
echo. >> "%REPORT%"
echo - **Cluster**: %CLUSTER% >> "%REPORT%"
echo - **Batch label**: %BATCH_LABEL% >> "%REPORT%"
echo - **Run log**: `%RUN_LOG%` >> "%REPORT%"
echo - **Exit code**: %RC% >> "%REPORT%"
echo. >> "%REPORT%"
echo ## Stage summary >> "%REPORT%"
echo. >> "%REPORT%"
echo ``` >> "%REPORT%"
findstr /B /C:"[OK]" /C:"Done in" /C:"WARN" "%RUN_LOG%" >> "%REPORT%" 2>nul
echo ``` >> "%REPORT%"
echo. >> "%REPORT%"
echo ## Quality flags >> "%REPORT%"
echo. >> "%REPORT%"
echo ``` >> "%REPORT%"
findstr /C:"anonymous" /C:"too thin" /C:"failed" "%RUN_LOG%" >> "%REPORT%" 2>nul
echo ``` >> "%REPORT%"
echo. >> "%REPORT%"
echo --- >> "%REPORT%"
echo Generated by `scripts\weekly_bse_pull.bat` via Task Scheduler. >> "%REPORT%"

REM --- desktop notification (popup at next login if any errors) ---
if not "%RC%"=="0" (
    msg %USERNAME% /TIME:60 "research-hub weekly BSE pull failed (rc=%RC%). See %REPORT%"
)

endlocal
exit /b %RC%
